server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
